/**
 * Build RESULTS.md from the run summaries on disk.
 *
 * Every number in the report is read out of a result file rather than typed, so a claim
 * in the write-up cannot drift from the run that produced it. Where an arm has been run
 * more than once, the most recent is used and the others are listed so nothing is
 * quietly dropped.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { BUCKET_SEVERITY, type Bucket, type EvalSummary, type CaseGrade } from "../lib/eval/grade";

interface RunFile {
  runId: string;
  arm: string;
  set: string;
  describes: string;
  at: string;
  gitSha: string;
  treeDirty?: boolean;
  /** Hash of everything an agent reads. Identifies a configuration exactly. */
  agentInputsSha256?: string;
  corpusManifestSha256: string;
  model: string | null;
  rulePack: { id: string; rules: number };
  summary: EvalSummary;
  grades: CaseGrade[];
}

const ARM_ORDER = ["b1-chatbot", "b2-steelman", "nightstop", "reference"];

const runs: RunFile[] = readdirSync("results")
  .map((d) => join("results", d, "summary.json"))
  .filter(existsSync)
  .map((p) => JSON.parse(readFileSync(p, "utf8")) as RunFile)
  .filter((r) => r.grades?.length >= 4)
  .sort((a, b) => a.at.localeCompare(b.at));

// Dev and held-out are reported separately and never pooled. A held-out score averaged
// into the development number is not a held-out score.
const latestIn = (set: string) => {
  const m = new Map<string, RunFile>();
  for (const r of runs.filter((x) => x.set === set)) m.set(r.arm, r);
  return ARM_ORDER.filter((a) => m.has(a)).map((a) => m.get(a)!);
};
const ordered = latestIn("dev");
const heldout = latestIn("heldout");

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const col = (r: RunFile, f: (s: EvalSummary) => string) => f(r.summary);

const lines: string[] = [
  "# Results",
  "",
  "Generated by `npm run report` from the files in `results/`. Every number here is read",
  "out of a run's `summary.json`, not typed — a figure in this document cannot drift from",
  "the run that produced it.",
  "",
  "## The arms",
  "",
  "| Arm | What it is given |",
  "|---|---|",
  ...ordered.map((r) => `| \`${r.arm}\` | ${r.describes} |`),
  "",
  "## Headline",
  "",
  "| Metric | " + ordered.map((r) => `\`${r.arm}\``).join(" | ") + " |",
  "|---|" + ordered.map(() => "---").join("|") + "|",
  "| **Trustworthy runs** (primary) | " +
    ordered.map((r) => col(r, (s) => `**${s.trustworthy}/${s.cases}**`)).join(" | ") + " |",
  "| **Silently wrong** (co-primary, target 0) | " +
    ordered.map((r) => col(r, (s) => `**${s.silentlyWrong}/${s.cases}**`)).join(" | ") + " |",
  "| Field-level parse accuracy | " +
    ordered.map((r) => col(r, (s) => pct(s.fieldAccuracy))).join(" | ") + " |",
  "| Conflict recall | " +
    ordered.map((r) => col(r, (s) => pct(s.conflictRecall))).join(" | ") + " |",
  "| False alarms raised | " +
    ordered.map((r) => col(r, (s) => String(s.falseAlarmCount))).join(" | ") + " |",
  "| Cost per roster (USD, list price) | " +
    ordered.map((r) => col(r, (s) => `$${(s.totalCostUsd / s.cases).toFixed(2)}`)).join(" | ") + " |",
  "| Wall clock per roster | " +
    ordered.map((r) => col(r, (s) => `${(s.totalWallMs / s.cases / 1000).toFixed(0)}s`)).join(" | ") + " |",
  "",
  "`reference` is not a baseline. It plans from ground-truth duties, so it answers the",
  "question the other numbers cannot: how much of any shortfall is the reading, and how",
  "much is the planning.",
  "",
  ...(() => {
    // The pre-registration commits to three repeats of the final arm and to reporting
    // all of them, so they are listed individually rather than averaged away.
    // A repeat is a re-run of the SAME configuration, anchored on the commit that CHANGED
    // the reader - not the one that reported the result, which lands after the run it
    // describes and would exclude that run from its own configuration. The run before the
    // reader was
    // asked to declare its derivations is a different system, and counting it as a
    // repeat would report variance that is actually a version difference.
    // Configuration identity comes from a hash of everything an agent reads, not from
    // the git SHA - a run started with uncommitted changes records the commit BEFORE
    // them, which made one run here look like a different system than it was.
    const all = runs.filter((r) => r.arm === "nightstop" && r.set === "dev");
    const current = all.filter((r) => r.agentInputsSha256).sort((a, b) => a.runId.localeCompare(b.runId)).pop()
      ?.agentInputsSha256;
    const reps = current ? all.filter((r) => r.agentInputsSha256 === current) : [];
    const earlier = all.filter((r) => !current || r.agentInputsSha256 !== current);
    if (reps.length < 2) return [];
    return [
      "## Repeats",
      "",
      `The final configuration run ${reps.length} times over the same eight cases. At n=8 a`,
      "single flake moves the primary by 12.5 points, so every run is listed rather than",
      "averaged. A repeat means an identical `agentInputsSha256` — a hash of every prompt,",
      "tool description and rule the agents read — rather than a matching commit, because a",
      "run started with uncommitted changes records the SHA of the commit before them.",
      "",
      "| Run | Trustworthy | Silently wrong | Field accuracy | Conflict recall | Cost |",
      "|---|---|---|---|---|---|",
      ...reps.map(
        (r) =>
          `| \`${r.runId.slice(-9)}\` | ${r.summary.trustworthy}/${r.summary.cases} | ` +
          `${r.summary.silentlyWrong}/${r.summary.cases} | ${pct(r.summary.fieldAccuracy)} | ` +
          `${pct(r.summary.conflictRecall)} | $${r.summary.totalCostUsd.toFixed(2)} |`,
      ),
      "",
      (() => {
        const t = new Set(reps.map((r) => r.summary.trustworthy));
        return t.size === 1
          ? `Identical on every run: **${[...t][0]}/${reps[0].summary.cases} trustworthy, ` +
            `0 silently wrong**, no variance across repeats.`
          : `Trustworthy count varies across repeats: ${reps.map((r) => r.summary.trustworthy).join(", ")}.`;
      })(),
      "",
      ...(earlier.length
        ? [
            "Other configurations, listed rather than dropped:",
            "",
            ...earlier.map(
              (r) =>
                `- \`${r.runId.slice(-9)}\` — ${r.summary.trustworthy}/${r.summary.cases} trustworthy, ` +
                `${r.summary.silentlyWrong} silently wrong` +
                (r.agentInputsSha256 ? "" : " (predates configuration hashing)"),
            ),
            "",
          ]
        : []),
    ];
  })(),
  ...(heldout.length
    ? [
        "## Held out",
        "",
        "Four cases generated from a separate seed **after every agent prompt was frozen**",
        "(commit `7b77a67`), and not run against until the final evaluation. Reported",
        "separately and never pooled with the development set — a held-out score averaged",
        "into the dev number is not a held-out score.",
        "",
        "| Metric | " + heldout.map((r) => `\`${r.arm}\``).join(" | ") + " |",
        "|---|" + heldout.map(() => "---").join("|") + "|",
        "| **Trustworthy runs** | " +
          heldout.map((r) => col(r, (s) => `**${s.trustworthy}/${s.cases}**`)).join(" | ") + " |",
        "| **Silently wrong** | " +
          heldout.map((r) => col(r, (s) => `**${s.silentlyWrong}/${s.cases}**`)).join(" | ") + " |",
        "| Field-level parse accuracy | " +
          heldout.map((r) => col(r, (s) => pct(s.fieldAccuracy))).join(" | ") + " |",
        "| Conflict recall | " +
          heldout.map((r) => col(r, (s) => pct(s.conflictRecall))).join(" | ") + " |",
        "| False alarms raised | " +
          heldout.map((r) => col(r, (s) => String(s.falseAlarmCount))).join(" | ") + " |",
        "",
        ...heldout.flatMap((r) => [
          `**\`${r.arm}\`, case by case** — run \`${r.runId}\``,
          "",
          "| Case | Bucket | Fields correct | Conflicts surfaced | False alarms |",
          "|---|---|---|---|---|",
          ...r.grades.map(
            (g) =>
              `| \`${g.caseId}\` | \`${g.bucket}\` | ${g.fieldsCorrect}/${g.fieldsTotal} | ` +
              `${g.surfacedCount}/${g.mandatoryTotal} | ${g.falseAlarms.length} |`,
          ),
          "",
        ]),
      ]
    : []),
  "## Where every case landed",
  "",
  "| Bucket | " + ordered.map((r) => `\`${r.arm}\``).join(" | ") + " |",
  "|---|" + ordered.map(() => "---").join("|") + "|",
  ...BUCKET_SEVERITY.map(
    (b) => `| \`${b}\` | ` + ordered.map((r) => String(r.summary.buckets[b as Bucket])).join(" | ") + " |",
  ),
  "",
];

for (const r of ordered) {
  lines.push(
    `### \`${r.arm}\` — case by case`,
    "",
    `Run \`${r.runId}\` · ${r.at.slice(0, 16).replace("T", " ")} · git \`${r.gitSha.slice(0, 8)}\`` +
      (r.model ? ` · ${r.model}` : " · no model") +
      ` · rule pack \`${r.rulePack.id}\` (${r.rulePack.rules} rules)`,
    "",
    "| Case | Bucket | Fields correct | Conflicts surfaced | False alarms | Cost |",
    "|---|---|---|---|---|---|",
    ...r.grades.map(
      (g) =>
        `| \`${g.caseId}\` | \`${g.bucket}\` | ${g.fieldsCorrect}/${g.fieldsTotal} | ` +
        `${g.surfacedCount}/${g.mandatoryTotal} | ${g.falseAlarms.length} | $${g.costUsd.toFixed(2)} |`,
    ),
    "",
  );
}

const shown = new Set([...ordered, ...heldout].map((r) => r.runId));
const superseded = runs.filter((r) => !shown.has(r.runId));
if (superseded.length) {
  lines.push(
    "## Earlier runs",
    "",
    "Kept rather than deleted. Listed so nothing is quietly dropped from the record.",
    "",
    ...superseded.map(
      (r) =>
        `- \`${r.runId}\` (${r.arm}, ${r.set}) — ${r.summary.trustworthy}/${r.summary.cases} trustworthy`,
    ),
    "",
  );
}

writeFileSync("RESULTS.md", lines.join("\n"));
console.log(
  `RESULTS.md — ${ordered.length} dev arms, ${heldout.length} held-out arms, ${runs.length} runs on disk`,
);
for (const r of [...ordered, ...heldout]) {
  console.log(
    `  ${r.set.padEnd(8)} ${r.arm.padEnd(14)} trustworthy ${r.summary.trustworthy}/${r.summary.cases}  ` +
    `silentlyWrong ${r.summary.silentlyWrong}  recall ${pct(r.summary.conflictRecall)}  ` +
    `falseAlarms ${r.summary.falseAlarmCount}`,
  );
}
