/**
 * Build RESULTS.md from the run summaries on disk.
 *
 * Every number in the report is read out of a result file rather than typed, so a claim
 * in the write-up cannot drift from the run that produced it. Where an arm has been run
 * more than once, the most recent is used and the others are listed so nothing is
 * quietly dropped.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { BUCKET_SEVERITY, type Bucket, type EvalSummary, type CaseGrade } from "../lib/eval/grade";

interface RunFile {
  runId: string;
  arm: string;
  set: string;
  describes: string;
  at: string;
  gitSha: string;
  corpusManifestSha256: string;
  model: string | null;
  rulePack: { id: string; rules: number };
  summary: EvalSummary;
  grades: CaseGrade[];
}

const ARM_ORDER = ["b1-chatbot", "b2-steelman", "nightstop", "reference"];

const runs: RunFile[] = readdirSync("results")
  .map((d) => join("results", d, "summary.json"))
  .filter(existsSync)
  .map((p) => JSON.parse(readFileSync(p, "utf8")) as RunFile)
  .filter((r) => r.grades?.length >= 8)
  .sort((a, b) => a.at.localeCompare(b.at));

const latest = new Map<string, RunFile>();
for (const r of runs) latest.set(r.arm, r);
const ordered = ARM_ORDER.filter((a) => latest.has(a)).map((a) => latest.get(a)!);

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const col = (r: RunFile, f: (s: EvalSummary) => string) => f(r.summary);

const lines: string[] = [
  "# Results",
  "",
  "Generated by `npm run report` from the files in `results/`. Every number here is read",
  "out of a run's `summary.json`, not typed — a figure in this document cannot drift from",
  "the run that produced it.",
  "",
  "## The arms",
  "",
  "| Arm | What it is given |",
  "|---|---|",
  ...ordered.map((r) => `| \`${r.arm}\` | ${r.describes} |`),
  "",
  "## Headline",
  "",
  "| Metric | " + ordered.map((r) => `\`${r.arm}\``).join(" | ") + " |",
  "|---|" + ordered.map(() => "---").join("|") + "|",
  "| **Trustworthy runs** (primary) | " +
    ordered.map((r) => col(r, (s) => `**${s.trustworthy}/${s.cases}**`)).join(" | ") + " |",
  "| **Silently wrong** (co-primary, target 0) | " +
    ordered.map((r) => col(r, (s) => `**${s.silentlyWrong}/${s.cases}**`)).join(" | ") + " |",
  "| Field-level parse accuracy | " +
    ordered.map((r) => col(r, (s) => pct(s.fieldAccuracy))).join(" | ") + " |",
  "| Conflict recall | " +
    ordered.map((r) => col(r, (s) => pct(s.conflictRecall))).join(" | ") + " |",
  "| False alarms raised | " +
    ordered.map((r) => col(r, (s) => String(s.falseAlarmCount))).join(" | ") + " |",
  "| Cost per roster (USD, list price) | " +
    ordered.map((r) => col(r, (s) => `$${(s.totalCostUsd / s.cases).toFixed(2)}`)).join(" | ") + " |",
  "| Wall clock per roster | " +
    ordered.map((r) => col(r, (s) => `${(s.totalWallMs / s.cases / 1000).toFixed(0)}s`)).join(" | ") + " |",
  "",
  "`reference` is not a baseline. It plans from ground-truth duties, so it answers the",
  "question the other numbers cannot: how much of any shortfall is the reading, and how",
  "much is the planning.",
  "",
  "## Where every case landed",
  "",
  "| Bucket | " + ordered.map((r) => `\`${r.arm}\``).join(" | ") + " |",
  "|---|" + ordered.map(() => "---").join("|") + "|",
  ...BUCKET_SEVERITY.map(
    (b) => `| \`${b}\` | ` + ordered.map((r) => String(r.summary.buckets[b as Bucket])).join(" | ") + " |",
  ),
  "",
];

for (const r of ordered) {
  lines.push(
    `### \`${r.arm}\` — case by case`,
    "",
    `Run \`${r.runId}\` · ${r.at.slice(0, 16).replace("T", " ")} · git \`${r.gitSha.slice(0, 8)}\`` +
      (r.model ? ` · ${r.model}` : " · no model") +
      ` · rule pack \`${r.rulePack.id}\` (${r.rulePack.rules} rules)`,
    "",
    "| Case | Bucket | Fields correct | Conflicts surfaced | False alarms | Cost |",
    "|---|---|---|---|---|---|",
    ...r.grades.map(
      (g) =>
        `| \`${g.caseId}\` | \`${g.bucket}\` | ${g.fieldsCorrect}/${g.fieldsTotal} | ` +
        `${g.surfacedCount}/${g.mandatoryTotal} | ${g.falseAlarms.length} | $${g.costUsd.toFixed(2)} |`,
    ),
    "",
  );
}

const superseded = runs.filter((r) => latest.get(r.arm)?.runId !== r.runId);
if (superseded.length) {
  lines.push(
    "## Earlier runs",
    "",
    "Kept rather than deleted. Listed so nothing is quietly dropped from the record.",
    "",
    ...superseded.map(
      (r) => `- \`${r.runId}\` (${r.arm}) — ${r.summary.trustworthy}/${r.summary.cases} trustworthy`,
    ),
    "",
  );
}

writeFileSync("RESULTS.md", lines.join("\n"));
console.log(`RESULTS.md — ${ordered.length} arms, ${runs.length} runs on disk`);
for (const r of ordered) {
  console.log(
    `  ${r.arm.padEnd(14)} trustworthy ${r.summary.trustworthy}/${r.summary.cases}  ` +
    `silentlyWrong ${r.summary.silentlyWrong}  recall ${pct(r.summary.conflictRecall)}  ` +
    `falseAlarms ${r.summary.falseAlarmCount}`,
  );
}
