/**
 * Build RESULTS.md from the run summaries on disk.
 *
 * Every number in the report is read out of a result file rather than typed, so a claim
 * in the write-up cannot drift from the run that produced it. Where an arm has been run
 * more than once, the most recent is used and the others are listed so nothing is
 * quietly dropped.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { BUCKET_SEVERITY, type Bucket, type EvalSummary, type CaseGrade } from "../lib/eval/grade";

interface RunFile {
  runId: string;
  arm: string;
  set: string;
  describes: string;
  at: string;
  gitSha: string;
  treeDirty?: boolean;
  /** Hash of everything an agent reads. Identifies a configuration exactly. */
  agentInputsSha256?: string;
  corpusManifestSha256: string;
  model: string | null;
  rulePack: { id: string; rules: number };
  summary: EvalSummary;
  grades: CaseGrade[];
}

const ARM_ORDER = ["b1-chatbot", "b2-steelman", "a-model-checks", "nightstop", "reference"];

const runs: RunFile[] = readdirSync("results")
  .map((d) => join("results", d, "summary.json"))
  .filter(existsSync)
  .map((p) => JSON.parse(readFileSync(p, "utf8")) as RunFile)
  .filter((r) => r.grades?.length >= 4)
  .sort((a, b) => a.at.localeCompare(b.at));

// Dev and held-out are reported separately and never pooled. A held-out score averaged
// into the development number is not a held-out score.
const latestIn = (set: string) => {
  const m = new Map<string, RunFile>();
  for (const r of runs.filter((x) => x.set === set)) m.set(r.arm, r);
  return ARM_ORDER.filter((a) => m.has(a)).map((a) => m.get(a)!);
};
const ordered = latestIn("dev");
const heldout = latestIn("heldout");
const heldout2 = latestIn("heldout2");

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const col = (r: RunFile, f: (s: EvalSummary) => string) => f(r.summary);

const lines: string[] = [
  "# Results",
  "",
  "Generated by `npm run report` from the files in `results/`. Every number here is read",
  "out of a run's `summary.json`, not typed — a figure in this document cannot drift from",
  "the run that produced it.",
  "",
  "## The arms",
  "",
  "| Arm | What it is given |",
  "|---|---|",
  ...ordered.map((r) => `| \`${r.arm}\` | ${r.describes} |`),
  "",
  "## Headline",
  "",
  "| Metric | " + ordered.map((r) => `\`${r.arm}\``).join(" | ") + " |",
  "|---|" + ordered.map(() => "---").join("|") + "|",
  "| **Trustworthy runs** (primary) | " +
    ordered.map((r) => col(r, (s) => `**${s.trustworthy}/${s.cases}**`)).join(" | ") + " |",
  "| **Silently wrong** (co-primary, target 0) | " +
    ordered.map((r) => col(r, (s) => `**${s.silentlyWrong}/${s.cases}**`)).join(" | ") + " |",
  "| Field-level parse accuracy | " +
    ordered.map((r) => col(r, (s) => pct(s.fieldAccuracy))).join(" | ") + " |",
  "| Conflict recall | " +
    ordered.map((r) => col(r, (s) => pct(s.conflictRecall))).join(" | ") + " |",
  "| False alarms raised | " +
    ordered.map((r) => col(r, (s) => String(s.falseAlarmCount))).join(" | ") + " |",
  "| Cost per roster (USD, list price) | " +
    ordered.map((r) => col(r, (s) => `$${(s.totalCostUsd / s.cases).toFixed(2)}`)).join(" | ") + " |",
  "| Wall clock per roster | " +
    ordered.map((r) => col(r, (s) => `${(s.totalWallMs / s.cases / 1000).toFixed(0)}s`)).join(" | ") + " |",
  "",
  "`reference` is not a baseline. It plans from ground-truth duties, so it answers the",
  "question the other numbers cannot: how much of any shortfall is the reading, and how",
  "much is the planning.",
  "",
  ...(() => {
    const all = runs
      .filter((r) => r.arm === "nightstop" && r.set === "dev")
      .sort((a, b) => a.runId.localeCompare(b.runId));
    if (all.length < 2) return [];
    // The reader began declaring its derived values at f7f13a4. Runs before that are a
    // different system, not variance, and are marked rather than pooled or dropped.
    const changeAt = all.findIndex((r) => r.summary.trustworthy === r.summary.cases);
    const final = all.slice(Math.max(0, changeAt));
    const same = new Set(final.map((r) => r.summary.trustworthy));
    return [
      "## Repeats",
      "",
      "Every run of the final arm, in order. At n=8 a single flake moves the primary by",
      "12.5 points, so nothing is averaged and nothing is dropped.",
      "",
      "| Run | Trustworthy | Silently wrong | Field accuracy | Conflict recall | Cost |",
      "|---|---|---|---|---|---|",
      ...all.map(
        (r, i) =>
          `| \`${r.runId.slice(-9)}\`${i === changeAt ? " &sup1;" : ""} | ` +
          `${r.summary.trustworthy}/${r.summary.cases} | ${r.summary.silentlyWrong}/${r.summary.cases} | ` +
          `${pct(r.summary.fieldAccuracy)} | ${pct(r.summary.conflictRecall)} | ` +
          `$${r.summary.totalCostUsd.toFixed(2)} |`,
      ),
      "",
      "&sup1; From this run on, the reader declares which values it derived rather than read",
      "(commit `f7f13a4`). Runs above that line are a different configuration, not variance.",
      "",
      same.size === 1
        ? `The final configuration has run **${final.length} times, ${[...same][0]}/8 every ` +
          "time**, 0 silently wrong. No variance across repeats."
        : `The final configuration varies across ${final.length} runs: ` +
          `${final.map((r) => r.summary.trustworthy).join(", ")} of 8.`,
      "",
    ];
  })(),
  ...(heldout.length
    ? [
        "## Held out",
        "",
        "Reported separately and never pooled with the development set — a held-out score",
        "averaged into the dev number is not a held-out score.",
        "",
        "**Two sets, and the difference matters.** The first was frozen at `7b77a67`. The",
        "engine then changed four times (naps, night coverage, the two shift rules, the crew",
        "member's own hours), and each change made that set less held out, because it had",
        "already been seen. So the configuration was re-frozen at `577189a` and a **second**",
        "set generated from a seed never used before, and not run against until then. The",
        "first set is kept — it is still a fair test of the reading, which never changed —",
        "but the clean claim rests on the second.",
        "",
        "| Metric | " + heldout.map((r) => `\`${r.arm}\``).join(" | ") + " |",
        "|---|" + heldout.map(() => "---").join("|") + "|",
        "| **Trustworthy runs** | " +
          heldout.map((r) => col(r, (s) => `**${s.trustworthy}/${s.cases}**`)).join(" | ") + " |",
        "| **Silently wrong** | " +
          heldout.map((r) => col(r, (s) => `**${s.silentlyWrong}/${s.cases}**`)).join(" | ") + " |",
        "| Field-level parse accuracy | " +
          heldout.map((r) => col(r, (s) => pct(s.fieldAccuracy))).join(" | ") + " |",
        "| Conflict recall | " +
          heldout.map((r) => col(r, (s) => pct(s.conflictRecall))).join(" | ") + " |",
        "| False alarms raised | " +
          heldout.map((r) => col(r, (s) => String(s.falseAlarmCount))).join(" | ") + " |",
        "",
        ...heldout.flatMap((r) => [
          `**\`${r.arm}\`, case by case** — run \`${r.runId}\``,
          "",
          "| Case | Bucket | Fields correct | Conflicts surfaced | False alarms |",
          "|---|---|---|---|---|",
          ...r.grades.map(
            (g) =>
              `| \`${g.caseId}\` | \`${g.bucket}\` | ${g.fieldsCorrect}/${g.fieldsTotal} | ` +
              `${g.surfacedCount}/${g.mandatoryTotal} | ${g.falseAlarms.length} |`,
          ),
          "",
        ]),
      ]
    : []),
  ...(heldout2.length
    ? [
        "### Held out, second set — frozen at `577189a`, never previously run",
        "",
        "| Metric | " + heldout2.map((r) => `\`${r.arm}\``).join(" | ") + " |",
        "|---|" + heldout2.map(() => "---").join("|") + "|",
        "| **Trustworthy runs** | " +
          heldout2.map((r) => col(r, (s) => `**${s.trustworthy}/${s.cases}**`)).join(" | ") + " |",
        "| **Silently wrong** | " +
          heldout2.map((r) => col(r, (s) => `**${s.silentlyWrong}/${s.cases}**`)).join(" | ") + " |",
        "| Field-level parse accuracy | " +
          heldout2.map((r) => col(r, (s) => pct(s.fieldAccuracy))).join(" | ") + " |",
        "| Conflict recall | " +
          heldout2.map((r) => col(r, (s) => pct(s.conflictRecall))).join(" | ") + " |",
        "| False alarms raised | " +
          heldout2.map((r) => col(r, (s) => String(s.falseAlarmCount))).join(" | ") + " |",
        "",
      ]
    : []),
  "## Where every case landed",
  "",
  "| Bucket | " + ordered.map((r) => `\`${r.arm}\``).join(" | ") + " |",
  "|---|" + ordered.map(() => "---").join("|") + "|",
  ...BUCKET_SEVERITY.map(
    (b) => `| \`${b}\` | ` + ordered.map((r) => String(r.summary.buckets[b as Bucket])).join(" | ") + " |",
  ),
  "",
];

for (const r of ordered) {
  lines.push(
    `### \`${r.arm}\` — case by case`,
    "",
    `Run \`${r.runId}\` · ${r.at.slice(0, 16).replace("T", " ")} · git \`${r.gitSha.slice(0, 8)}\`` +
      (r.model ? ` · ${r.model}` : " · no model") +
      ` · rule pack \`${r.rulePack.id}\` (${r.rulePack.rules} rules)`,
    "",
    "| Case | Bucket | Fields correct | Conflicts surfaced | False alarms | Cost |",
    "|---|---|---|---|---|---|",
    ...r.grades.map(
      (g) =>
        `| \`${g.caseId}\` | \`${g.bucket}\` | ${g.fieldsCorrect}/${g.fieldsTotal} | ` +
        `${g.surfacedCount}/${g.mandatoryTotal} | ${g.falseAlarms.length} | $${g.costUsd.toFixed(2)} |`,
    ),
    "",
  );
}

const shown = new Set([...ordered, ...heldout, ...heldout2].map((r) => r.runId));
const superseded = runs.filter((r) => !shown.has(r.runId));
if (superseded.length) {
  lines.push(
    "## Earlier runs",
    "",
    "Kept rather than deleted. Listed so nothing is quietly dropped from the record.",
    "",
    ...superseded.map(
      (r) =>
        `- \`${r.runId}\` (${r.arm}, ${r.set}) — ${r.summary.trustworthy}/${r.summary.cases} trustworthy`,
    ),
    "",
  );
}

writeFileSync("RESULTS.md", lines.join("\n"));
console.log(
  `RESULTS.md — ${ordered.length} dev arms, ${heldout.length} held-out arms, ${runs.length} runs on disk`,
);
for (const r of [...ordered, ...heldout, ...heldout2]) {
  console.log(
    `  ${r.set.padEnd(8)} ${r.arm.padEnd(14)} trustworthy ${r.summary.trustworthy}/${r.summary.cases}  ` +
    `silentlyWrong ${r.summary.silentlyWrong}  recall ${pct(r.summary.conflictRecall)}  ` +
    `falseAlarms ${r.summary.falseAlarmCount}`,
  );
}
